[versions]

core = 		        "1.16.0"
lifecycle = 	    "2.8.7"
datastoreprefs =    "1.1.6" # 1.1.5 has a bug! (https://issuetracker.google.com/issues/413061399)
startup =           "1.2.0"
activity = 		    "1.10.1"

[libraries]

core = 				        { module = "androidx.core:core-ktx", 						version.ref = "core" }
lifecycle = 		        { module = "androidx.lifecycle:lifecycle-runtime-ktx", 		version.ref = "lifecycle" }
lifecycle-compose =         { module = "androidx.lifecycle:lifecycle-runtime-compose", 	version.ref = "lifecycle" }
datastore-preferences = 	{ module = "androidx.datastore:datastore-preferences", 	    version.ref = "datastoreprefs" }
startup = 		            { module = "androidx.startup:startup-runtime", 	            version.ref = "startup" }
activity-compose =          { module = "androidx.activity:activity-compose", 			version.ref = "activity" }