[versions]

# mflisar (local snapshot: "LOCAL-SNAPSHOT")
kmp-parcelize =             "1.0.1"
kmpdevtools =               "6.4.2" # change via "updateDevToolsVersion" gradle task!
democomposables =           "1.0.2"
cachefileprovider =         "1.0.0"

# others
compose-unstyled =          "1.49.5"

[plugins]

# mflisar
kmpdevtools-buildplugin =               { id = "io.github.mflisar.kmpdevtools.plugins-build-gradle",    version.ref = "kmpdevtools" }

[libraries]

# mflisar
kmp-parcelize =                         { module = "io.github.mflisar.parcelize:library", 	            version.ref = "kmp-parcelize" }
kmpdevtools-core =                      { module = "io.github.mflisar.kmpdevtools:core",                version.ref = "kmpdevtools" }
democomposables =                       { module = "io.github.mflisar.democomposables:library",         version.ref = "democomposables" }
cachefileprovider =                     { module = "io.github.mflisar.cachefileprovider:library", 	    version.ref = "cachefileprovider" }

# others
composeunstyled-theming =               { module = "com.composables:composeunstyled-theming",           version.ref = "compose-unstyled" }
composeunstyled-primitives =            { module = "com.composables:composeunstyled-primitives",        version.ref = "compose-unstyled" }
composeunstyled-platformtheme =         { module = "com.composables:composeunstyled-platformtheme",     version.ref = "compose-unstyled" }


