name: Publish to Maven Central
on:
  release:
    types: [published]

env:
  TAG: ${{ github.event.release.tag_name }}

jobs:
  publish:
    name: Publish to Maven Central
    runs-on: macos-latest

    steps:

      # 1) Repo checkout
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      # 2) set up JDK
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      # 3) make gradle executable
      - name: Grant Permission to Execute Gradle
        run: chmod +x gradlew

      # 4) set up gradle
      - name: Set up Gradle (with caching)
        uses: gradle/actions/setup-gradle@v3

      # 5) Publish Library
      - name: Publish Library
        run: |
          echo "TAG: $TAG"
          echo "Publishing library ðŸš€"
          echo ""
          ./gradlew publish --no-daemon --no-parallel
          echo "Publishedâœ…"

          # echo "Releasing repository... ðŸš€"
          # ./gradlew closeAndReleaseRepository
          # echo "Releasedâœ…"
        env:
          ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.GPG_KEY }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.GPG_PASSWORD }}
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}