name: Build and Doploy Dokka API documentation

on:
  push:
    branches: [ main ]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  dokka:
    name: Build Dokka
    runs-on: ubuntu-latest

    steps:

      # 1) Repo checkout
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      # 2) set up JDK
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      # 3) make gradle executable
      - name: Grant Permission to Execute Gradle
        run: chmod +x gradlew

      # 4) set up gradle
      - name: Set up Gradle (with caching)
        uses: gradle/actions/setup-gradle@v3

      # 5) Build Dokka HTML
      - name: Build Dokka HTML
        run: ./gradlew :library:dokka:dokkaGenerate

      # 6) Upload Pages artifact
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: library/dokka/build/dokka/html

  deploy:
    name: Deploy Dokka
    needs: dokka
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
