name: Update markdown files

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: write

jobs:

  update-docs:
    name: Update markdown files
    runs-on: ubuntu-latest

    steps:

      # 1) Repo checkout
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      # 2) set up JDK
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      # 3) make gradle executable
      - name: Grant Permission to Execute Gradle
        run: chmod +x gradlew

      # 4) set up gradle
      - name: Set up Gradle (with caching)
        uses: gradle/actions/setup-gradle@v3

      # 5) run gradle task
      - name: Run Gradle update task
        run: ./gradlew updateMarkdownFiles

      # 6) MarkdownSnippets - install
      - name: Setup .NET (for MarkdownSnippets.Tool)
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      # 7) MarkdownSnippets - Snippets in .md updaten
      - name: Run MarkdownSnippets
        run: |
          dotnet tool install --global MarkdownSnippets.Tool
          echo "$HOME/.dotnet/tools" >> $GITHUB_PATH
          mdsnippets --convention InPlaceOverwrite --omit-snippet-links true

      # 8) Linkcheck (Markdown, Bilder, intern/extern)
      - name: Check links with Lychee
        uses: lycheeverse/lychee-action@v2
        with:
          # Passe die Globs/Args an dein Repo an
          args: --root-dir "$(pwd)" --verbose --no-progress './**/*.md' './**/*.html'
        env:
          # hilft gegen GitHub rate limiting bei github.com Links
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # 9) Lychee-Ordner löschen (Cleanup)
      - name: Remove lychee folder
        run: rm -rf lychee

      # 10) Änderungen committen
      - name: Commit & push changes (if any)
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add -A
            git commit -m "update-docs: Automated markdown docs update [skip ci]"
            git push
          else
            echo "No changes to commit."
          fi